displayName=Quetzal Keybinds
author=ctrlcam
description=Keybinds for quetzal menu
tags=quetzal,menu,transport,travel,navigation,teleport,map,qol,keybinds,hotkeys
plugins=com.quetzalkeybinds.QuetzaKeybindsPlugin